name: yestech_flutter
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 8.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.3
  provider: ^5.0.0
  path_provider: ^2.0.2
  open_appstore: ^1.0.2
  new_version: ^0.2.1
  version: ^2.0.0
  get: ^4.2.4
  get_storage: ^2.0.3
  device_info: ^2.0.2
  flutter_styled_toast: ^2.0.0

  #firebase
  firebase_auth: ^2.0.0
  firebase_core: ^1.3.0
  firebase_analytics: ^8.1.2
  cloud_firestore: ^2.3.0
  firebase_storage: ^9.0.0
  firebase_database: ^7.1.1
  firebase_messaging: ^10.0.3

  badges: ^2.0.1
  shared_preferences: ^2.0.6
  package_info: ^2.0.2
  font_awesome_flutter: ^9.1.0
  webview_flutter: ^2.0.9
  launch_review: ^3.0.1
  html: ^0.15.0
  flutter_spinkit: ^5.0.0
  sizer: ^2.0.13
  page_view_indicators: ^2.0.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/images/appicon.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik-Black.ttf
        - asset: assets/fonts/Rubik-BlackItalic.ttf
        - asset: assets/fonts/Rubik-Bold.ttf
        - asset: assets/fonts/Rubik-BoldItalic.ttf
        - asset: assets/fonts/Rubik-Italic.ttf
        - asset: assets/fonts/Rubik-Light.ttf
        - asset: assets/fonts/Rubik-LightItalic.ttf
        - asset: assets/fonts/Rubik-Medium.ttf
        - asset: assets/fonts/Rubik-MediumItalic.ttf
        - asset: assets/fonts/Rubik-Regular.ttf
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Regular.ttf
          weight: 400
        - asset: assets/fonts/Nunito-Light.ttf
          weight: 300
        - asset: assets/fonts/Nunito-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Nunito-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Nunito-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Nunito-Bold.ttf
          weight: 700
